<?php
namespace Steven;

require '../vendor/autoload.php';

use Steven\Cache\SessionCache;

session_start();

class Get extends SessionCache{
    protected $sessionPrefix = 'XX_';

    public function save($id, $data, $lifeTime = 0)
    {
        parent::save($id, $data, $lifeTime); // TODO: Change the autogenerated stub
    }
}

$cache = new Get();
$cache->save('name', 'steven');
echo $cache->fetch('name');
var_dump($_SESSION);